# set status-utf8 on
# set utf8 on

set -g prefix C-k

set -g default-terminal "screen-256color"

set -g mouse off
setw -g mode-keys vi

set -g base-index 1
set -g pane-base-index 1

setenv -g TMUX_PLUGIN_MANAGER_PATH "$HOME/.config/tmux/plugins/"


# List of plugins
# set -g @plugin 'tmux-plugins/tpm'
# set -g @plugin 'tmux-plugins/tmux-sensible'
# set -g @plugin 'tmux-plugins/tmux-resurrect'
# run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux

bind j send-keys -R

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
# run '$HOME/.config/tmux/plugins/tpm/tpm'
